const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"科室管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKeshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"心里调护类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXinlitiaohu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"食疗类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZongyishiliao"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"护理管理",
                        "menuJump":"列表",
                        "tableName":"huli"
                    }
                ],
                "menu":"护理管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"缴费信息管理",
                        "menuJump":"列表",
                        "tableName":"jiaofei"
                    }
                ],
                "menu":"缴费信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"来访登记管理",
                        "menuJump":"列表",
                        "tableName":"laifangdengji"
                    }
                ],
                "menu":"来访登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"日程安排管理",
                        "menuJump":"列表",
                        "tableName":"richenganpai"
                    }
                ],
                "menu":"日程安排管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"心里调护管理",
                        "menuJump":"列表",
                        "tableName":"xinlitiaohu"
                    }
                ],
                "menu":"心里调护管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                ],
                "menu":"医生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"老人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yuangong"
                    }
                ],
                "menu":"员工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"预约挂号管理",
                        "menuJump":"列表",
                        "tableName":"yuyueguahao"
                    }
                ],
                "menu":"预约挂号管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"中药信息管理",
                        "menuJump":"列表",
                        "tableName":"zhongyao"
                    }
                ],
                "menu":"中药信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出入库管理",
                        "menuJump":"列表",
                        "tableName":"zhongyaoChuruInout"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出入库详情管理",
                        "menuJump":"列表",
                        "tableName":"zhongyaoChuruInoutList"
                    }
                ],
                "menu":"出入库管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"中医诊断管理",
                        "menuJump":"列表",
                        "tableName":"zhongyizhenduan"
                    }
                ],
                "menu":"中医诊断管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"中医食疗管理",
                        "menuJump":"列表",
                        "tableName":"zongyishiliao"
                    }
                ],
                "menu":"中医食疗管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"病例管理",
	                    "menuJump":"列表",
	                    "tableName":"bingli"
	                }
	            ],
	            "menu":"病例管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"日程安排管理",
	                    "menuJump":"列表",
	                    "tableName":"richenganpai"
	                }
	            ],
	            "menu":"日程安排管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"心里调护管理",
	                    "menuJump":"列表",
	                    "tableName":"xinlitiaohu"
	                }
	            ],
	            "menu":"心里调护管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"审核"
	                    ],
	                    "menu":"预约挂号管理",
	                    "menuJump":"列表",
	                    "tableName":"yuyueguahao"
	                }
	            ],
	            "menu":"预约挂号管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"中药信息管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyao"
	                }
	            ],
	            "menu":"中药信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"修改"
	                    ],
	                    "menu":"中医诊断管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyizhenduan"
	                }
	            ],
	            "menu":"中医诊断管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"中医食疗管理",
	                    "menuJump":"列表",
	                    "tableName":"zongyishiliao"
	                }
	            ],
	            "menu":"中医食疗管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"医生",
	    "tableName":"yisheng"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"病例管理",
	                    "menuJump":"列表",
	                    "tableName":"bingli"
	                }
	            ],
	            "menu":"病例管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"缴费信息管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaofei"
	                }
	            ],
	            "menu":"缴费信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"来访登记管理",
	                    "menuJump":"列表",
	                    "tableName":"laifangdengji"
	                }
	            ],
	            "menu":"来访登记管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"日程安排管理",
	                    "menuJump":"列表",
	                    "tableName":"richenganpai"
	                }
	            ],
	            "menu":"日程安排管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"心里调护管理",
	                    "menuJump":"列表",
	                    "tableName":"xinlitiaohu"
	                }
	            ],
	            "menu":"心里调护管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"医生管理",
	                    "menuJump":"列表",
	                    "tableName":"yisheng"
	                }
	            ],
	            "menu":"医生管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"预约挂号管理",
	                    "menuJump":"列表",
	                    "tableName":"yuyueguahao"
	                }
	            ],
	            "menu":"预约挂号管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"中医诊断管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyizhenduan"
	                }
	            ],
	            "menu":"中医诊断管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"中医食疗管理",
	                    "menuJump":"列表",
	                    "tableName":"zongyishiliao"
	                }
	            ],
	            "menu":"中医食疗管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"老人",
	    "tableName":"yonghu"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"来访登记管理",
	                    "menuJump":"列表",
	                    "tableName":"laifangdengji"
	                }
	            ],
	            "menu":"来访登记管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"心里调护管理",
	                    "menuJump":"列表",
	                    "tableName":"xinlitiaohu"
	                }
	            ],
	            "menu":"心里调护管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"中药信息管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyao"
	                }
	            ],
	            "menu":"中药信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"出入库管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyaoChuruInout"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"出入库详情管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyaoChuruInoutList"
	                }
	            ],
	            "menu":"出入库管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"中医食疗管理",
	                    "menuJump":"列表",
	                    "tableName":"zongyishiliao"
	                }
	            ],
	            "menu":"中医食疗管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"员工",
	    "tableName":"yuangong"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"病例管理",
	                    "menuJump":"列表",
	                    "tableName":"bingli"
	                }
	            ],
	            "menu":"病例管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"缴费信息管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaofei"
	                }
	            ],
	            "menu":"缴费信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"来访登记管理",
	                    "menuJump":"列表",
	                    "tableName":"laifangdengji"
	                }
	            ],
	            "menu":"来访登记管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"日程安排管理",
	                    "menuJump":"列表",
	                    "tableName":"richenganpai"
	                }
	            ],
	            "menu":"日程安排管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"心里调护管理",
	                    "menuJump":"列表",
	                    "tableName":"xinlitiaohu"
	                }
	            ],
	            "menu":"心里调护管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"老人管理",
	                    "menuJump":"列表",
	                    "tableName":"yonghu"
	                }
	            ],
	            "menu":"老人管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"预约挂号管理",
	                    "menuJump":"列表",
	                    "tableName":"yuyueguahao"
	                }
	            ],
	            "menu":"预约挂号管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"中药信息管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyao"
	                }
	            ],
	            "menu":"中药信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"中医诊断管理",
	                    "menuJump":"列表",
	                    "tableName":"zhongyizhenduan"
	                }
	            ],
	            "menu":"中医诊断管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"中医食疗管理",
	                    "menuJump":"列表",
	                    "tableName":"zongyishiliao"
	                }
	            ],
	            "menu":"中医食疗管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"护理",
	    "tableName":"huli"
	}
]
    }
}
export default menu;
